### ISSUE TITLE
Facebook stopped returning results for type=post when the "Accept-Language" HTTP header is missing or "wrong"

### ISSUE THREAD

**Issue by oyvindsk** [rizen/Facebook-Graph#34]
Looks like a bug on Facebook's end.

Faceook::Graph suddenly stopped returning results for type=post searches, on different versions and different machines. 

After some digging, it turns out that this works:
    `curl -v -H "Accept-Language: en-us,no;q=0.5"  "https://graph.facebook.com/search?q=Foobar&type=post"` 

but this does not:
    `curl -v  "https://graph.facebook.com/search?q=Foobar&type=post"`

**Comment by rizen** [comment]
I'm unable to replicate in Facebook::Graph 1.1000
