### ISSUE TITLE
Facebook v2 API

### ISSUE THREAD

**Issue by rizen** [rizen/Facebook-Graph#53]
Got this message from a user:

I am using Facebook::Graph Perl module for long time to authorize users on a website, recently I am getting message on Facebook site saying:
 
You must upgrade this app to Graph API v2.x
v1.0 will be deprecated on April 30, 2015
Learn how to upgrade

**Comment by ashamza** [comment]
Is there a way to upgrade? I mean it might be easier for some people to upgrade instead of migrate to another module

**Comment by Eckankar** [comment]
e76bad479 attempted to add versioning, but in fact didn't change a thing. (The module still sends unversioned requests, as evidenced by the tests.)

The reason for this is, that the URI is used as follows:

    my $uri = $self->uri;
    $uri->path('oauth/access_token');

i.e., the path is overridden on use, and thus the v2.1 doesn't persist anywhere it's used.

To actually switch it over to using the v2.1 API, one could change the 'Facebook::Graph::Role::Uri` function to be something like:

    sub uri {
        my ($self, $path) = @_;
    
        my $uri = URI->new('https://graph.facebook.com/');
        $uri->path_segments("v2.1", split (qr#/#, $path // "") );
        return $uri;
    }

and changing everywhere it's used from

    my $uri = $self->uri;
    $uri->path('oauth/access_token');

to

    my $uri = $self->uri('oauth/access_token');

Whether or not that takes care of all the issues, I do not know, but it's a good starting point for making the requests versioned.

**Comment by rizen** [comment]
Fixed in version 1.1000
