### ISSUE TITLE
Facebook API o Facebook:Graph bug with new updating post (photo and message) method?

### ISSUE THREAD

**Issue by thebluenobody** [rizen/Facebook-Graph#57]
Hello rizen! First the first... Thanks for your work. Now, one question... Before, my posts with photo and message (caption) published with Facebook::Graph were perfect... From the last two days there is a little problem, the posts are published as "edited", first with the photo and second update with the body text on a message field. I guess this is related to update of the Facebook Graph API that allows the updates in the posts via api calls. The question is, is a normal behavior or a bug? if is it a bug? a module bug? or a facebook api bug? Note: with Facebook:OpenGraph (request) is the same. The "only text" posts (well, "only message" no photo) are published normally. Is like if api or module first publish the photo without message and after the message in a post update of the photo. 

Again thanks. Sorry for my very very basic english.

**Comment by rizen** [comment]
No idea, but since the Facebook::Graph module hasn’t changed it’s almost a 99% certainty that it is a change in the Facebook APIs.

**Comment by thebluenobody** [comment]
Thanks for answering. I already was supposed to be a matter of updating the Facebook API, but better ask. I will keep researching and testing. Greetings.
