### ISSUE TITLE
Risk of security.

### ISSUE THREAD

**Issue by worthmine** [rizen/Facebook-Graph#60]
this module is using Ouch. so with Plack/PSGI, it seems having a risk of security.

```
        my $fb = Facebook::Graph->new(
            app_id => ‘your_app_id',
            secret => ‘your_app_key_secret',
        );
        $fb->authorize;
        $fb->access_token( $fb->app_id . '|' .$fb->secret );
        my $q = $fb->query->find(‘*some facebookID*'} )
            ->select_fields(qw( id name ))
            ->request
            ->as_hashref;
```

if ‘*some facebookID*’ was incorrect - not exists, unavailable or ID of person not page - then PSGI error page leaks the error with access token like bellow…

```
Could not execute request (https://graph.facebook.com/v2.2/*some facebookID*?fields=id%2Cname&access_token=***%7C***): OAuthException - (#803) Some of the aliases you requested do not exist: *some facebookID* at /usr/local/share/perl5/Facebook/Graph/Response.pm line 37.
at /usr/local/share/perl5/Ouch.pm line 28
```

using `eval{}` is a silver bullet. But I think there must be the better way to fix it.

**Comment by rizen** [comment]
I'm discontinuing all development of this module in favor of https://metacpan.org/pod/Facebook::OpenGraph

**Comment by worthmine** [comment]
thanks for replying. I will take a look.
