### ISSUE TITLE
pagination?

### ISSUE THREAD

**Issue by akarelas-pt** [rizen/Facebook-Graph#64]
When I get search results from graph.facebook.com by using the API, I get a before and after field, under the pagination property, for pagination (ie to get the next or previous batch of results).

I wonder how I can use those values when making calls with Facebook::Graph...

I tried adding ?after=.... to the first parameter of $fb->fetch, but that returned an error.

So, what am I to do, if I want to get all the results?

Also: would it be possible for your module to go through all of the result pages, so that I don't have to code that?

Thanks.

**Comment by rizen** [comment]
Sorry, I'm not in a position to provide any support for the module. If you want to submit a patch as a pull request I'd push it out for you, but that's as far as I can do.
