### ISSUE TITLE
v3.1 vs. v2.8

### ISSUE THREAD

**Issue by eserte** [rizen/Facebook-Graph#76]
Test suite fails on all of my smoker systems:
```
...
#   Failed test 'get an api version'
#   at t/01_versioned_path.t line 14.
#          got: 'v3.1'
#     expected: 'v2.8'
... (etc) ...
```

**Comment by rizen** [comment]
I'm discontinuing all development of this module in favor of  https://metacpan.org/pod/Facebook::OpenGraph
